apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: supply-chain-risk-agent
  annotations:
    scenarios.ai.sap.com/id: "supply-chain-risk"
    executables.ai.sap.com/id: "risk-predictor-exec"
    executables.ai.sap.com/name: "supply-chain-risk-predictor"
  labels:
    scenarios.ai.sap.com/id: "supply-chain-risk"
    ai.sap.com/version: "v1"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    spec: |
      predictor:
        containers:
        - name: kserve-container
          image: "docker.io/mohameddyn0/supply-chain-agent:v2"
          ports:
            - containerPort: 8080
              protocol: "TCP"
          envFrom:
            - secretRef:
                name: genai-secret
          env:
            - name: AICORE_TRACKING_ID
              value: "v1"