import os
import requests
from dotenv import load_dotenv

# Load environment variables first
load_dotenv()

# Import the SAP GenAI Hub proxy
from gen_ai_hub.proxy.native.openai import chat


def generate_email_text(shipment: dict, probability: float) -> str:
    """
    Sends shipment data to SAP Generative AI Hub to draft a mitigation email.
    """
    # 1. Define the prompt for the LLM
    prompt = f"""
    You are a Supply Chain Risk Assistant.
    A shipment has been flagged with a high risk of delay.
    
    Details:
    - Requisition ID: {shipment.get('Requisition_ID')}
    - Vendor: {shipment.get('Vendor')}
    - Shipment Mode: {shipment.get('ShipmentMode')}
    - Processing Time: {shipment.get('ProcessingTime')} days
    - Delay Risk Probability: {probability * 100:.1f}%
    
    Draft a professional and concise email to the Supply Chain Manager "Mohamed". 
    Alert them about this risk and suggest an actionable mitigation strategy 
    (e.g., changing shipment mode to Air Freight, contacting the vendor immediately).
    Do not include placeholders like [Mohamed], just the email body.
    """
    
    try:
        # 2. Call the Generative AI Hub API
        # FIXED: Replaced 'model_name' with your specific 'deployment_id'
        response = chat.completions.create(
            deployment_id="d070af417a8a2304", 
            messages=[
                {"role": "system", "content": "You are a professional supply chain AI assistant."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.3, # Low temperature for professional, deterministic output
            max_tokens=150
        )
        
        # Extract and return the generated text
        email_content = response.choices[0].message.content
        return email_content
        
    except Exception as e:
        print(f"Error calling Generative AI Hub: {e}")
        # Fallback message in case the LLM API fails
        return f"URGENT: High risk of delay detected for PR {shipment.get('Requisition_ID')}. Please review the system immediately."


def send_real_email(body: str, subject: str):
    """
    Sends the generated email text via Formspree.
    """
    formspree_url = "https://formspree.io/f/xojpaoez"

    payload = {
        "subject": subject,
        "message": body,
        "to": "dynmedo28@gmail.com" 
    }

    try:
        response = requests.post(formspree_url, json=payload)
        if response.status_code == 200:
            print("✅ Email sent successfully via Formspree!")
        else:
            print(f"❌ Formspree Error: {response.text}")
    except Exception as e:
        print(f"❌ Error: {e}")


def draft_and_send_email(shipment: dict, probability: float):
    """
    Background task triggered by the FastAPI endpoint.
    Generates the text using GenAI Hub and sends it via email.
    """
    # 1. Generate the email body using LLM
    email_body = generate_email_text(shipment, probability)
    
    # 2. Log to console for local debugging
    print("\n" + "="*50)
    print("EMAIL GENERATED BY GENAI HUB:")
    print("="*50)
    print(email_body)
    print("="*50 + "\n")
    
    # 3. Send the actual email
    subject = f"Action Required: High Delay Risk for PR {shipment.get('Requisition_ID')}"
    send_real_email(body=email_body, subject=subject)